spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: s3cret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
